version: '3.8'

services:
  nginx:
    container_name: nginx
    depends_on:
      - nest
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/home/node/app

  nest:
    container_name: nest
    build:
      context: ./nest
    env_file:
      - ./nest/.development.env
    volumes:
      - ./nest:/app
      - ./nest/node_modules:/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0.28-oracle
    env_file:
      - ./nest/.development.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
